<a href="https://colab.research.google.com/github/NishigandhaChoudhury/Neural-Network-and-Deep-Learning-Lab-Experiments/blob/main/NNDLLAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
tensor_0d = np.array(5)
print(tensor_0d)
print("0-D Tensor (Scalar):")
print("Dimensions:", tensor_0d.ndim)
print("Shape:", tensor_0d.shape)
print()

5
0-D Tensor (Scalar):
Dimensions: 0
Shape: ()



In [ ]:
tensor_1d = np.array([1, 2, 3, 4])
print("1-D Tensor (Vector):")
print(tensor_1d)
print("Dimensions:", tensor_1d.ndim)
print("Shape:", tensor_1d.shape)
print()

1-D Tensor (Vector):
[1 2 3 4]
Dimensions: 1
Shape: (4,)



In [ ]:
tensor_2d = np.array([[1, 2, 3],
                      [4, 5, 6]])
print("2-D Tensor (Matrix):")
print(tensor_2d)
print("Dimensions:", tensor_2d.ndim)
print("Shape:", tensor_2d.shape)
print()

2-D Tensor (Matrix):
[[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)



In [ ]:
tensor_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3-D Tensor:")
print(tensor_3d)
print("Dimensions:", tensor_3d.ndim)
print("Shape:", tensor_3d.shape)
print()

3-D Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Shape: (2, 2, 2)



In [ ]:
tensor_4d = np.zeros((2, 3, 4, 5))
print("4-D Tensor:")
print("Dimensions:", tensor_4d.ndim)
print("Shape:", tensor_4d.shape)

4-D Tensor:
Dimensions: 4
Shape: (2, 3, 4, 5)
